version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DBPASSWORD}
      - MYSQL_DATABASE=fastapi-vue-template
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"


  admin:
    image: phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${DBPASSWORD}
    ports:
      - "8080:80"

  app:
    container_name: backend
    build: .    
    command: bash -c "chmod +x wait-for-it.sh && ./wait-for-it.sh db:3306 --timeout=30 --strict -- python3 backend/db_init.py && python3 backend/main.py"
    # command: bash -c "python3 backend/db_init.py && uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"
    # command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    depends_on:
      - db
      